In [10]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [12]:
movies_data = pd.read_csv("C:\\Users\\ABINASH\OneDrive\\Desktop\\movies.csv")

In [13]:
movies_data.head()


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [14]:
movies_data.shape

(4803, 24)

In [15]:
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [16]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [17]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799                                                  NaN
4800                                                  NaN
4801                                                  NaN
4802                                                  NaN
Length: 4803, dtype: object


In [19]:
combined_features = combined_features.dropna()
combined_features = combined_features.fillna('')
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)


  (0, 2059)	0.1701479649518548
  (0, 6661)	0.11429421237668091
  (0, 11113)	0.19659464365709167
  (0, 8725)	0.16231873789167722
  (0, 7469)	0.23688181493087848
  (0, 12479)	0.1528997976336656
  (0, 14239)	0.19539014255433562
  (0, 12000)	0.20190521307222728
  (0, 11358)	0.2208017329558662
  (0, 14773)	0.20823298735110954
  (0, 14551)	0.2329808254780701
  (0, 11385)	0.14977293661066507
  (0, 9805)	0.26936700729904856
  (0, 9534)	0.08734535805520414
  (0, 14542)	0.12593255607069875
  (0, 13042)	0.0662280667693844
  (0, 4238)	0.23688181493087848
  (0, 12186)	0.2139246902011623
  (0, 2744)	0.25244839623226556
  (0, 14165)	0.1263712397025473
  (0, 12278)	0.33706405674362216
  (0, 5016)	0.16231873789167722
  (0, 2603)	0.2234527578396162
  (0, 3151)	0.2183472672840518
  (0, 4672)	0.10162340157558672
  :	:
  (3756, 6649)	0.1630164373294472
  (3756, 8312)	0.16780336056424186
  (3756, 7615)	0.18714779291826822
  (3756, 2219)	0.14997884476607481
  (3756, 3621)	0.14997884476607481
  (3756, 7262)	0

In [20]:
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.06798628 0.03717966 ... 0.00395593 0.01660447 0.0321408 ]
 [0.06798628 1.         0.03129961 ... 0.01041746 0.         0.00377777]
 [0.03717966 0.03129961 1.         ... 0.         0.         0.01083266]
 ...
 [0.00395593 0.01041746 0.         ... 1.         0.00252605 0.01171968]
 [0.01660447 0.         0.         ... 0.00252605 1.         0.00319347]
 [0.0321408  0.00377777 0.01083266 ... 0.01171968 0.00319347 1.        ]]


In [21]:
print(similarity.shape)

(3757, 3757)


In [22]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Pirates of the Caribbean: At World's End	


In [28]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [29]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

["Pirates of the Caribbean: At World's End", "Pirates of the Caribbean: Dead Man's Chest", 'Pirates of the Caribbean: On Stranger Tides']


In [30]:
close_match = find_close_match[0]
print(close_match)

Pirates of the Caribbean: At World's End


In [31]:

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1


In [32]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.06798628042892609), (1, 1.0000000000000002), (2, 0.03129961415859582), (3, 0.018797668652626408), (4, 0.03170423139533768), (5, 0.09418272021687162), (6, 0.01361719220970536), (7, 0.019063684615056743), (8, 0.03859273805501952), (9, 0.028857867984649094), (10, 0.026499917277128207), (11, 0.5329832797326393), (12, 0.15890020857771076), (13, 0.054529325606098224), (14, 0.022847120876143566), (15, 0.01809998864869643), (16, 0.08512681703000682), (17, 0.01618164866578657), (18, 0.057479280841962715), (19, 0.08346692473223681), (20, 0.015849961200598117), (21, 0.044511165044248284), (22, 0.04093019673868691), (23, 0.06506939950787785), (24, 0.0), (25, 0.019542063300811555), (26, 0.14278830065347814), (27, 0.05841519967825217), (28, 0.01962073876715134), (29, 0.09344374043669433), (30, 0.04140081086903123), (31, 0.08535602954365232), (32, 0.018955382145739323), (33, 0.0), (34, 0.019884636850041815), (35, 0.017907805963029686), (36, 0.025154023158282773), (37, 0.029874480334235905), (3

In [33]:
len(similarity_score)

3757

In [34]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(1, 1.0000000000000002), (191, 0.5477557247089783), (11, 0.5329832797326393), (1543, 0.1887868207465057), (371, 0.18152134585465468), (122, 0.15930479898352945), (12, 0.15890020857771076), (2659, 0.15290074223350378), (2676, 0.15152587218946803), (317, 0.14617617564806096), (170, 0.14603800435682643), (26, 0.14278830065347814), (1865, 0.14169861749944285), (314, 0.1381675389180986), (1124, 0.13684169960670983), (258, 0.1350800450717717), (1870, 0.13498056710856798), (2056, 0.13434792462086), (2235, 0.1335895076911349), (1038, 0.13268372765624248), (1751, 0.12914039554268875), (855, 0.1283592502352858), (1526, 0.12556995158055817), (1010, 0.12506183748904984), (806, 0.1248699293723101), (2265, 0.12452820739499398), (253, 0.12177392398490275), (500, 0.12172005889451792), (1012, 0.12112268126991023), (2154, 0.12096666623427942), (1471, 0.12075148048148232), (181, 0.11954130663138714), (2496, 0.11920321664660692), (847, 0.11900501772155864), (1474, 0.11364742984003506), (2270, 0.113330043

In [37]:
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Avatar
2 . Big Hero 6
3 . Ladyhawke
4 . Baby Geniuses
5 . X-Men: Days of Future Past
6 . The One
7 . After the Sunset
8 . Star Wars: Episode II - Attack of the Clones
9 . Broken City
10 . The Others
11 . Inkheart
12 . Body of Lies
13 . Forsaken
14 . Our Kind of Traitor
15 . The Boxtrolls
16 . R.I.P.D.
17 . The Next Three Days
18 . The Man in the Iron Mask
19 . Toy Story 3
20 . The Princess and the Frog
21 . Beowulf
22 . Toy Story
23 . Made of Honor
24 . The Perks of Being a Wallflower
25 . Invaders from Mars
26 . You've Got Mail
27 . Shine
28 . Reign of Assassins
29 . Gangster Squad


In [38]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Avatar
Movies suggested for you : 

1 . Avatar
2 . Big Hero 6
3 . Ladyhawke
4 . Baby Geniuses
5 . X-Men: Days of Future Past
6 . The One
7 . After the Sunset
8 . Star Wars: Episode II - Attack of the Clones
9 . Broken City
10 . The Others
11 . Inkheart
12 . Body of Lies
13 . Forsaken
14 . Our Kind of Traitor
15 . The Boxtrolls
16 . R.I.P.D.
17 . The Next Three Days
18 . The Man in the Iron Mask
19 . Toy Story 3
20 . The Princess and the Frog
21 . Beowulf
22 . Toy Story
23 . Made of Honor
24 . The Perks of Being a Wallflower
25 . Invaders from Mars
26 . You've Got Mail
27 . Shine
28 . Reign of Assassins
29 . Gangster Squad
